### ISSUE TITLE
Zooming (w.r.t. Vertical axis) doesn't work.

### ISSUE THREAD

**Issue by mahnerak** [aimhubio/aimui#156]
Zoom tool seems to work only for the horizontal axis.

https://user-images.githubusercontent.com/1367529/103237768-13a2ef80-4962-11eb-8c3c-fb296724487d.mov

**Comment by gorarakelyan** [comment]
Hi @mahnerak,

Thanks for the feedback. We are looking into it.

**Comment by gorarakelyan** [comment]
This issue was resolved in the newer version(1.2.6). You can upgrade to the latest stable version by running `aim upgrade` from the command line.

Please try out and check if it works.
